project:
  type: website
  output-dir: docs
website:
  title: "Kevin's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



